class _BotCommands:
    def __init__(self):
        self.StartCommand = 'startbot'
        self.MirrorCommand = 'mirrorbot'
        self.UnzipMirrorCommand = 'unzipmirrorbot'
        self.TarMirrorCommand = 'tarmirrorbot'
        self.CancelMirror = 'cancelbot'
        self.CancelAllCommand = 'cancelallbot'
        self.ListCommand = 'listbot'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'usersbot'
        self.AuthorizeCommand = 'authorizebot'
        self.UnAuthorizeCommand = 'unauthorizebot'
        self.AddSudoCommand = 'addsudobot'
        self.RmSudoCommand = 'rmsudobot'
        self.PingCommand = 'pingbot'
        self.RestartCommand = 'restartbot'
        self.StatsCommand = 'statsbot'
        self.HelpCommand = 'helpbot'
        self.LogCommand = 'logbot'
        self.SpeedCommand = 'speedtestbot'
        self.CloneCommand = 'clonebot'
        self.CountCommand = 'countbot'
        self.WatchCommand = 'watchbit'
        self.TarWatchCommand = 'tarwatchbot'
        self.DeleteCommand = 'delbot'
        self.UsageCommand = 'usagebot'
        self.MediaInfoCommand = 'mediainfobot'
        self.ConfigMenuCommand = 'configbot'
        self.ShellCommand = 'shellbot'
        self.UpdateCommand = 'updatebot'

BotCommands = _BotCommands()
